# Generated by Django 4.2.4 on 2023-08-28 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Juzgado Policía Local Villa Alemana', 'Juzgado Policía Local Villa Alemana'), ('Fiscalía Local Villa Alemana', 'Fiscalía Local Villa Alemana'), ('Propietario', 'Propietario'), ('Fiscales', 'Fiscales')], max_length=60, unique=True, verbose_name='Nombre de Tribunal')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunales',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Automovil', 'Automovil'), ('Station Wagon', 'Station Wagon'), ('Camioneta', 'Camioneta'), ('Furgón', 'Furgón'), ('Jeep', 'Jeep'), ('Motocicleta', 'Motocicleta')], max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('placa_patente', models.CharField(max_length=6, unique=True)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=40)),
                ('imagen', models.ImageField(upload_to='vehiculos')),
                ('motivo', models.CharField(choices=[('Robo', 'Robo'), ('Robo con intimidación', 'Robo con intimidación'), ('Robo lugar habitado', 'Robo lugar habitado'), ('Robo lugar no habitado', 'Robo lugar no habitado'), ('Robo frustrado', 'Robo frustrado'), ('Hurto', 'Hurto'), ('Apropiación indebida', 'Apropiación indebida'), ('Secuestro', 'Secuestro'), ('Receptación', 'Receptación'), ('Microtráfico de drogas', 'Microtráfico de drogas'), ('Tráfico de drogas', 'Tráfico de drogas'), ('Receptación y ley 20.000', 'Receptación y ley 20.000'), ('Hallazgo de vehículo', 'Hallazgo de vehículo'), ('Encargo de vehículo (Robo)', 'Encargo de vehículo (Robo)'), ('Encargo de vehículo (Hurto)', 'Encargo de vehículo (Hurto)'), ('Encargo de vehículo (Apropiación indebida)', 'Encargo de vehículo (Apropiación indebida)'), ('Participación en accidente de tránsito (Solo daños)', 'Participación en accidente de tránsito (Solo daños)'), ('Participación en accidente de tránsito (Lesiones leves)', 'Participación en accidente de tránsito (Lesiones leves)'), ('Participación en accidente de tránsito (lesiones menos graves)', 'Participación en accidente de tránsito (lesiones menos graves)'), ('Participación en accidente de tránsito (Lesiones graves)', 'Participación en accidente de tránsito (Lesiones graves)'), ('Participación en accidente de tránsito (Resultado de muerte)', 'Participación en accidente de tránsito (Resultado de muerte)'), ('Participación en accidente de tránsito (Abandono de vehículo)', 'Participación en accidente de tránsito (Abandono de vehículo)'), ('Cuasidelito de homicidio', 'Cuasidelito de homicidio'), ('Clonación de placa patente', 'Clonación de placa patente'), ('Adulteración de nro. de chasis', 'Adulteración de nro. de chasis'), ('Falsificación de instrumento público', 'Falsificación de instrumento público'), ('Conducción estado ebriedad', 'Conducción estado ebriedad'), ('Conducción bajo influencia del alcohol', 'Conducción bajo influencia del alcohol'), ('Abandono de vehículo en vía pública', 'Abandono de vehículo en vía pública'), ('Documentación vencida', 'Documentación vencida'), ('Conducir vehículo motorizado sin portar licencia de conductor', 'Conducir vehículo motorizado sin portar licencia de conductor'), ('Conducir vehículo motorizado sin haber obtenido licencia de conductor', 'Conducir vehículo motorizado sin haber obtenido licencia de conductor'), ('Documentación vencida y sin licencia de conductor', 'Documentación vencida y sin licencia de conductor'), ('No portar documentación al momento de ser fiscalizado', 'No portar documentación al momento de ser fiscalizado'), ('Conducir vehículo motorizado sin sus placas patentes', 'Conducir vehículo motorizado sin sus placas patentes')], max_length=100)),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('numero_de_parte', models.IntegerField(blank=True, null=True, verbose_name='Número parte')),
                ('numero_de_oficio', models.IntegerField(blank=True, null=True, verbose_name='Número oficio')),
                ('acta_entrega', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('observaciones', models.TextField(blank=True, default='Sin observaciones')),
                ('entregado', models.BooleanField(default=False)),
                ('registro_propietario', models.BooleanField(default=False)),
                ('disposicion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tribunal', to_field='nombre', verbose_name='Disposición')),
                ('funcionario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario_entrega', to=settings.AUTH_USER_MODEL)),
                ('funcionario_receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario_receptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Propietario_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=30)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo', to_field='placa_patente', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Propietario vehiculo',
                'verbose_name_plural': 'Propietarios de vehículos',
            },
        ),
        migrations.CreateModel(
            name='Entrega_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_oficio', models.IntegerField(verbose_name='Número oficio')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, default='Sin observaciones')),
                ('fecha_entrega_vehiculo', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo', to_field='placa_patente', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Entrega de vehículo',
                'verbose_name_plural': 'Entregas de vehículos',
            },
        ),
    ]
