# Generated by Django 4.2.4 on 2023-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Automovil', 'Automovil'), ('Station Wagon', 'Station Wagon'), ('Camioneta', 'Camioneta'), ('Furgón', 'Furgón'), ('Jeep', 'Jeep'), ('Motocicleta', 'Motocicleta'), ('Otros', 'Otros')], max_length=60),
        ),
    ]
