# Generated by Django 4.0 on 2023-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='motivo',
            field=models.CharField(choices=[('Robo', 'Robo'), ('Robo con intimidación', 'Robo con intimidación'), ('Robo lugar habitado', 'Robo lugar habitado'), ('Robo lugar no habitado', 'Robo lugar no habitado'), ('Robo frustrado', 'Robo frustrado'), ('Hurto', 'Hurto'), ('Apropiación indebida', 'Apropiación indebida'), ('Secuestro', 'Secuestro'), ('Receptación', 'Receptación'), ('Microtráfico de drogas', 'Microtráfico de drogas'), ('Tráfico de drogas', 'Tráfico de drogas'), ('Receptación y ley 20.000', 'Receptación y ley 20.000'), ('Hallazgo de vehículo', 'Hallazgo de vehículo'), ('Encargo de vehículo (Robo)', 'Encargo de vehículo (Robo)'), ('Encargo de vehículo (Hurto)', 'Encargo de vehículo (Hurto)'), ('Encargo de vehículo (Apropiación indebida)', 'Encargo de vehículo (Apropiación indebida)'), ('Participación en accidente de tránsito (Solo daños)', 'Participación en accidente de tránsito (Solo daños)'), ('Participación en accidente de tránsito (Lesiones leves)', 'Participación en accidente de tránsito (Lesiones leves)'), ('Participación en accidente de tránsito (lesiones menos graves)', 'Participación en accidente de tránsito (lesiones menos graves)'), ('Participación en accidente de tránsito (Lesiones graves)', 'Participación en accidente de tránsito (Lesiones graves)'), ('Participación en accidente de tránsito (Resultado de muerte)', 'Participación en accidente de tránsito (Resultado de muerte)'), ('Participación en accidente de tránsito (Abandono de vehículo)', 'Participación en accidente de tránsito (Abandono de vehículo)'), ('Cuasidelito de homicidio', 'Cuasidelito de homicidio'), ('Clonación de placa patente', 'Clonación de placa patente'), ('Adulteración de nro. de chasis', 'Adulteración de nro. de chasis'), ('Falsificación de instrumento público', 'Falsificación de instrumento público'), ('Conducción estado ebriedad', 'Conducción estado ebriedad'), ('Conducción bajo influencia del alcohol', 'Conducción bajo influencia del alcohol'), ('Abandono de vehículo en vía pública', 'Abandono de vehículo en vía pública'), ('Documentación vencida', 'Documentación vencida'), ('Conducir vehículo motorizado sin portar licencia de conductor', 'Conducir vehículo motorizado sin portar licencia de conductor'), ('Conducir vehículo motorizado sin haber obtenido licencia de conductor', 'Conducir vehículo motorizado sin haber obtenido licencia de conductor'), ('Documentación vencida y sin licencia de conductor', 'Documentación vencida y sin licencia de conductor'), ('No portar documentación al momento de ser fiscalizado', 'No portar documentación al momento de ser fiscalizado'), ('Conducir vehículo motorizado sin sus placas patentes', 'Conducir vehículo motorizado sin sus placas patentes'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
