# Generated by Django 4.2.5 on 2023-09-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehiculo_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='nombre',
            field=models.CharField(choices=[('Juzgado Policía Local', 'Juzgado Policía Local'), ('Fiscalía Local', 'Fiscalía Local'), ('Propietario', 'Propietario'), ('Fiscales', 'Fiscales')], max_length=60, unique=True, verbose_name='Nombre de Tribunal'),
        ),
    ]
