# Generated by Django 4.2.4 on 2023-08-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_usuario', '0005_alter_user_codigo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(choices=[('Carabinero', 'Carabinero'), ('Cabo 2do.', 'Cabo 2do.'), ('Cabo 1ro.', 'Cabo 1ro.')], max_length=10),
        ),
    ]
